# Generated by Django 4.0.1 on 2022-02-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
